// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: t89_lvgl9_2

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

// Implemented in GaugeUpdater.cpp — forwards the Screen4 slider value to the
// CAN layer (pump target temp command to the sensor node).
void ui_pump_target_changed(int32_t targetC);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
