// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

static void ui_event_menubutton_to_screen2(lv_event_t * e)
{
    _ui_screen_change(&ui_Screen2, LV_SCREEN_LOAD_ANIM_NONE, 0, 0, &ui_Screen2_screen_init);
}

void ui_comp_menubutton_create_hook(lv_obj_t * comp)
{
    lv_obj_add_event_cb(comp, ui_event_menubutton_to_screen2, LV_EVENT_CLICKED, NULL);
}

static void ui_event_dashboardbutton_to_screen1(lv_event_t * e)
{
    _ui_screen_change(&ui_Screen1, LV_SCREEN_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
}

void ui_comp_dashboardbutton_create_hook(lv_obj_t * comp)
{
    lv_obj_add_event_cb(comp, ui_event_dashboardbutton_to_screen1, LV_EVENT_CLICKED, NULL);
}

void ui_comp_settingsbutton_create_hook(lv_obj_t * comp)
{
    // Hook will be used to attach specific event callbacks based on button context
}
