// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: t89_lvgl9_2

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

// Forward declarations for event callbacks
static void ui_event_screen1_to_screen2(lv_event_t * e);
static void ui_event_screen2_to_screen1(lv_event_t * e);
static void ui_event_screen1_to_screen3(lv_event_t * e);

void ui_init(void)
{
    ui_comp_init();

    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui_Screen4_screen_init();
    ui_Screen5_screen_init();
    ui_Screen6_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);

    lv_disp_load_scr(ui_Screen1);
}

void ui_destroy(void)
{
    ui_Screen1_screen_destroy();
    ui_Screen2_screen_destroy();
    ui_Screen3_screen_destroy();
    ui_Screen4_screen_destroy();
    ui_Screen5_screen_destroy();
    ui_Screen6_screen_destroy();
}

// Event callbacks
static void ui_event_screen1_to_screen2(lv_event_t * e)
{
    _ui_screen_change(&ui_Screen2, LV_SCREEN_LOAD_ANIM_NONE, 0, 0, &ui_Screen2_screen_init);
}

static void ui_event_screen2_to_screen1(lv_event_t * e)
{
    _ui_screen_change(&ui_Screen1, LV_SCREEN_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
}

void ui_event_settingsbutton_to_screen3(lv_event_t * e)
{
    _ui_screen_change(&ui_Screen3, LV_SCREEN_LOAD_ANIM_NONE, 0, 0, &ui_Screen3_screen_init);
}

void ui_event_settingsbutton_to_screen4(lv_event_t * e)
{
    _ui_screen_change(&ui_Screen4, LV_SCREEN_LOAD_ANIM_NONE, 0, 0, &ui_Screen4_screen_init);
}

void ui_event_settingsbutton_to_screen5(lv_event_t * e)
{
    _ui_screen_change(&ui_Screen5, LV_SCREEN_LOAD_ANIM_NONE, 0, 0, &ui_Screen5_screen_init);
}

void ui_event_settingsbutton_to_screen6(lv_event_t * e)
{
    _ui_screen_change(&ui_Screen6, LV_SCREEN_LOAD_ANIM_NONE, 0, 0, &ui_Screen6_screen_init);
}
