// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: t89_lvgl9_2

#ifndef _T89_LVGL9_2_UI_H
#define _T89_LVGL9_2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#define DISPLAY_NODE_VERSION "1.3.0"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"
#include "screens/ui_Screen2.h"
#include "screens/ui_Screen3.h"
#include "screens/ui_Screen4.h"
#include "screens/ui_Screen5.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_966466731);    // assets/Group 1 (1).png
LV_IMG_DECLARE(ui_img_group_2_png);    // assets/Group 2.png
LV_IMG_DECLARE(ui_img_group_3_png);    // assets/Group 3.png
LV_IMG_DECLARE(ui_img_37416093);    // assets/rpm_knobL (1).png
LV_IMG_DECLARE(ui_img_title_png);    // assets/title.png
LV_IMG_DECLARE(ui_img_rpmedge_png);    // assets/rpmedge.png
LV_IMG_DECLARE(ui_img_0_png);    // assets/0.png
LV_IMG_DECLARE(ui_img_2_png);    // assets/2.png
LV_IMG_DECLARE(ui_img_4_png);    // assets/4.png
LV_IMG_DECLARE(ui_img_6_png);    // assets/6.png
LV_IMG_DECLARE(ui_img_8_png);    // assets/8.png
LV_IMG_DECLARE(ui_img_14_png);    // assets/14.png
LV_IMG_DECLARE(ui_img_12_png);    // assets/12.png
LV_IMG_DECLARE(ui_img_10_png);    // assets/10.png
LV_IMG_DECLARE(ui_img_1878767743);    // assets/CAR (1).png
extern const lv_image_dsc_t clutch;    // Clutch plate image
extern const lv_image_dsc_t pot_ver_knob;    // Vertical potentiometer knob

// FONTS
LV_FONT_DECLARE(ui_font_DSEG20);
LV_FONT_DECLARE(ui_font_DSEG48);
LV_FONT_DECLARE(ui_font_DSEG7classicitalic);
LV_FONT_DECLARE(ui_font_DSEG60);
LV_FONT_DECLARE(ui_font_DSEG72);
LV_FONT_DECLARE(ui_font_DSEG86);
LV_FONT_DECLARE(ui_font_EXO2);
LV_FONT_DECLARE(ui_font_EXO2_128);
LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_inkfree40);
LV_FONT_DECLARE(ui_font_inkfree402);
LV_FONT_DECLARE(lv_font_montserrat_20);

// UI INIT
void ui_init(void);
void ui_destroy(void);

// Event callbacks
void ui_event_settingsbutton_to_screen3(lv_event_t * e);
void ui_event_settingsbutton_to_screen4(lv_event_t * e);
void ui_event_settingsbutton_to_screen5(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
