// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: t89_lvgl9_2

#include "../ui.h"
#include "ui_scale.h"   /* 1.25x layout scale for the 1024x600 panel */

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Container1 = NULL;
//lv_obj_t * ui_scale3 = NULL;
lv_obj_t * ui_gaugerpm = NULL;
lv_obj_t * ui_headerimg = NULL;
lv_obj_t * ui_gaugefuel = NULL;
lv_obj_t * ui_gaugetemp_eng = NULL;
lv_obj_t * ui_gaugetemp = NULL;
lv_obj_t * ui_gaugetemp_radout = NULL;
lv_obj_t * ui_rpmbottom = NULL;
lv_obj_t * ui_rpmtop = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_Image14 = NULL;
lv_obj_t * ui_Image13 = NULL;
lv_obj_t * ui_Image12 = NULL;
lv_obj_t * ui_Image11 = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_Image9 = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_gearnum = NULL;
lv_obj_t * ui_stackedgears = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_Button6 = NULL;
lv_obj_t * ui_Button7 = NULL;
lv_obj_t * ui_gaugefuel1 = NULL;
lv_obj_t * ui_scalefuel1 = NULL;
lv_obj_t * ui_scaletemp_eng = NULL;
lv_obj_t * ui_scaletemp = NULL;
lv_obj_t * ui_scaletemp_radout = NULL;
lv_obj_t * ui_menubutton = NULL;


// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x081418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_size(ui_Container1, 800, 120);
    lv_obj_set_pos(ui_Container1, 0, -40);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_gaugerpm = lv_slider_create(ui_Container1);
    lv_slider_set_range(ui_gaugerpm, 0, 14000);
    lv_slider_set_value(ui_gaugerpm, 6500, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_gaugerpm) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_gaugerpm, 0, LV_ANIM_OFF);
    lv_obj_set_size(ui_gaugerpm, 700, 122);
    lv_obj_set_align(ui_gaugerpm, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_gaugerpm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_gaugerpm, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gaugerpm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_gaugerpm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_gaugerpm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_gaugerpm, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_gaugerpm, lv_color_hex(0x0EC7f0), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gaugerpm, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_gaugerpm, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_gaugerpm, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_gaugerpm, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gaugerpm, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_gaugerpm, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_gaugerpm, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_gaugerpm, &ui_img_37416093, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_gaugerpm, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_gaugerpm,
                                                                                               lv_obj_get_style_pad_right(ui_gaugerpm, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_headerimg = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_headerimg, &ui_img_title_png);
    lv_obj_set_size(ui_headerimg, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
    lv_obj_set_pos(ui_headerimg, 0, -11);
    lv_obj_set_align(ui_headerimg, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_headerimg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_headerimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_gaugefuel = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_gaugefuel, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_gaugefuel, 0, LV_ANIM_OFF);
    lv_obj_set_size(ui_gaugefuel, 30, 180);
    lv_obj_set_pos(ui_gaugefuel, 210, 140);
    lv_obj_set_align(ui_gaugefuel, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_gaugefuel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_gaugefuel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gaugefuel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_gaugefuel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_gaugefuel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_gaugefuel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_gaugefuel, lv_color_hex(0x0492D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_gaugefuel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_gaugefuel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_gaugefuel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_gaugefuel, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_gaugefuel, lv_color_hex(0xF07010), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gaugefuel, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_gaugefuel, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_gaugefuel, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_gaugefuel,
                                                                                                lv_obj_get_style_pad_right(ui_gaugefuel, LV_PART_MAIN) + 1, LV_PART_MAIN);

    // Three temperature gauges, left to right: engine, radiator (Dallas
    // DS18B20), radiator outlet. Geometry, colours and styling all live in
    // components/ui_comp_temp_gauge.{c,h} — only the x offset differs here.
    ui_temp_gauge_t g_eng    = ui_temp_gauge_create(ui_Screen1, -UI_TEMP_GAUGE_PITCH * 2 - 130);
    ui_temp_gauge_t g_rad    = ui_temp_gauge_create(ui_Screen1, -UI_TEMP_GAUGE_PITCH - 130);
    ui_temp_gauge_t g_radout = ui_temp_gauge_create(ui_Screen1, -130);
    ui_gaugetemp_eng     = g_eng.bar;     ui_scaletemp_eng     = g_eng.scale;
    ui_gaugetemp         = g_rad.bar;     ui_scaletemp         = g_rad.scale;
    ui_gaugetemp_radout  = g_radout.bar;  ui_scaletemp_radout  = g_radout.scale;

  
                                                                                
    ui_rpmbottom = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_rpmbottom, &ui_img_rpmedge_png);
    lv_obj_set_size(ui_rpmbottom, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
    lv_obj_set_pos(ui_rpmbottom, 0, 26);
    lv_obj_set_align(ui_rpmbottom, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rpmbottom, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_rpmbottom, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rpmtop = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_rpmtop, &ui_img_rpmedge_png);
    lv_obj_set_size(ui_rpmtop, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
    lv_obj_set_pos(ui_rpmtop, 0, -107);
    lv_obj_set_align(ui_rpmtop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rpmtop, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_rpmtop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image7 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image7, &ui_img_0_png);
    lv_obj_set_size(ui_Image7, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
    lv_obj_set_pos(ui_Image7, -354, -39);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);

    ui_Image14 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image14, &ui_img_2_png);
    lv_obj_set_size(ui_Image14, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
    lv_obj_set_pos(ui_Image14, -256, -39);
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);

    ui_Image13 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image13, &ui_img_4_png);
    lv_obj_set_size(ui_Image13, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
    lv_obj_set_pos(ui_Image13, -153, -39);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);

    ui_Image12 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image12, &ui_img_6_png);
    lv_obj_set_size(ui_Image12, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
    lv_obj_set_pos(ui_Image12, -55, -39);
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);

    ui_Image11 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image11, &ui_img_8_png);
    lv_obj_set_size(ui_Image11, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
    lv_obj_set_pos(ui_Image11, 47, -39);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);

    ui_Image10 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image10, &ui_img_14_png);
    lv_obj_set_size(ui_Image10, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
    lv_obj_set_pos(ui_Image10, 346, -39);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);

    ui_Image9 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image9, &ui_img_12_png);
    lv_obj_set_size(ui_Image9, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
    lv_obj_set_pos(ui_Image9, 245, -39);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);

    ui_Image8 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image8, &ui_img_10_png);
    lv_obj_set_size(ui_Image8, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
    lv_obj_set_pos(ui_Image8, 148, -38);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);

    ui_gearnum = lv_label_create(ui_Screen1);
    lv_obj_set_size(ui_gearnum, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
    lv_obj_set_pos(ui_gearnum, 0, 165);
    lv_obj_set_align(ui_gearnum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gearnum, "6");
    lv_obj_set_style_text_color(ui_gearnum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gearnum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gearnum, &ui_font_EXO2_128, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_gearnum, lv_color_hex(0xFA0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_gearnum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_gearnum, lv_color_hex(0x16E524), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_gearnum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Stacked downshift indicator — small gears to the left of the main gear number
    ui_stackedgears = lv_label_create(ui_Screen1);
    lv_obj_set_size(ui_stackedgears, 260, LV_SIZE_CONTENT);
    lv_obj_set_pos(ui_stackedgears, -180, 165);
    lv_obj_set_align(ui_stackedgears, LV_ALIGN_CENTER);
    lv_label_set_text(ui_stackedgears, "");
    lv_obj_set_style_text_color(ui_stackedgears, lv_color_hex(0xFF9800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_stackedgears, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_stackedgears, &ui_font_DSEG48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_stackedgears, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

// Replace Button1 (center red button)
ui_Button1 = lv_led_create(ui_Screen1);
lv_obj_set_size(ui_Button1, 100, 40);
lv_obj_set_pos(ui_Button1, 0, -150);
lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
lv_led_set_color(ui_Button1, lv_color_hex(0xFF0000));
lv_led_set_brightness(ui_Button1, 255);
lv_obj_set_style_border_width(ui_Button1, 5, LV_PART_MAIN);
lv_obj_set_style_border_color(ui_Button1, lv_color_hex(0xFFFF00), LV_PART_MAIN);
lv_obj_set_style_border_opa(ui_Button1, 255, LV_PART_MAIN);
lv_led_off(ui_Button1);

// Replace Button2 (left purple)
ui_Button2 = lv_led_create(ui_Screen1);
lv_obj_set_size(ui_Button2, 40, 40);
lv_obj_set_pos(ui_Button2, -90, -145);
lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
lv_led_set_color(ui_Button2, lv_color_hex(0xD569E6));
lv_led_set_brightness(ui_Button2, 255);
lv_obj_set_style_border_width(ui_Button2, 5, LV_PART_MAIN);
lv_obj_set_style_border_color(ui_Button2, lv_color_hex(0xFFFF00), LV_PART_MAIN);
lv_obj_set_style_border_opa(ui_Button2, 255, LV_PART_MAIN);
lv_led_off(ui_Button2);

// Replace Button3 (right purple)
ui_Button3 = lv_led_create(ui_Screen1);
lv_obj_set_size(ui_Button3, 40, 40);
lv_obj_set_pos(ui_Button3, 90, -145);
lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
lv_led_set_color(ui_Button3, lv_color_hex(0xD569E6));
lv_led_set_brightness(ui_Button3, 255);
lv_obj_set_style_border_width(ui_Button3, 5, LV_PART_MAIN);
lv_obj_set_style_border_color(ui_Button3, lv_color_hex(0xFFFF00), LV_PART_MAIN);
lv_obj_set_style_border_opa(ui_Button3, 255, LV_PART_MAIN);
lv_led_off(ui_Button3);

// Replace Button4 (center left cyan)
ui_Button4 = lv_led_create(ui_Screen1);
lv_obj_set_size(ui_Button4, 60, 15);
lv_obj_set_pos(ui_Button4, -165, -145);
lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
lv_led_set_color(ui_Button4, lv_color_hex(0x41BACD));
lv_led_set_brightness(ui_Button4, 255);
lv_obj_set_style_border_width(ui_Button4, 5, LV_PART_MAIN);
lv_obj_set_style_border_color(ui_Button4, lv_color_hex(0xFFFF00), LV_PART_MAIN);
lv_obj_set_style_border_opa(ui_Button4, 255, LV_PART_MAIN);
lv_led_off(ui_Button4);

// Replace Button6 (right-center cyan)
ui_Button6 = lv_led_create(ui_Screen1);
lv_obj_set_size(ui_Button6, 60, 15);
lv_obj_set_pos(ui_Button6, 165, -145);
lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
lv_led_set_color(ui_Button6, lv_color_hex(0x41BACD));
lv_led_set_brightness(ui_Button6, 255);
lv_obj_set_style_border_width(ui_Button6, 5, LV_PART_MAIN);
lv_obj_set_style_border_color(ui_Button6, lv_color_hex(0xFFFF00), LV_PART_MAIN);
lv_obj_set_style_border_opa(ui_Button6, 255, LV_PART_MAIN);
lv_led_off(ui_Button6);

// Replace Button7 (far left cyan)
ui_Button7 = lv_led_create(ui_Screen1);
lv_obj_set_size(ui_Button7, 60, 15);
lv_obj_set_pos(ui_Button7, -245, -145);
lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
lv_led_set_color(ui_Button7, lv_color_hex(0x41BACD));
lv_led_set_brightness(ui_Button7, 255);
lv_obj_set_style_border_width(ui_Button7, 5, LV_PART_MAIN);
lv_obj_set_style_border_color(ui_Button7, lv_color_hex(0xFFFF00), LV_PART_MAIN);
lv_obj_set_style_border_opa(ui_Button7, 255, LV_PART_MAIN);
lv_led_off(ui_Button7);

// Replace Button5 (far right cyan)
ui_Button5 = lv_led_create(ui_Screen1);
lv_obj_set_size(ui_Button5, 60, 15);
lv_obj_set_pos(ui_Button5, 245, -145);
lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
lv_led_set_color(ui_Button5, lv_color_hex(0x41BACD));
lv_led_set_brightness(ui_Button5, 255);
lv_obj_set_style_border_width(ui_Button5, 5, LV_PART_MAIN);
lv_obj_set_style_border_color(ui_Button5, lv_color_hex(0xFFFF00), LV_PART_MAIN);
lv_obj_set_style_border_opa(ui_Button5, 255, LV_PART_MAIN);
lv_led_off(ui_Button5);


    // (ui_gaugetemp1 / ui_scaletemp1 removed: an orphaned 4th temp bar + 0-100
    //  scale left over from the SquareLine export. Nothing drove them, and they
    //  sat directly on top of the radiator-outlet gauge.)
                                                                                       
    
    ui_gaugefuel1 = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_gaugefuel1, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_gaugefuel1, 0, LV_ANIM_OFF);
    lv_obj_set_size(ui_gaugefuel1, 40, 180);
    lv_obj_set_pos(ui_gaugefuel1, 143, 140);
    lv_obj_set_align(ui_gaugefuel1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_gaugefuel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_gaugefuel1, lv_color_hex(0xfffb93), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gaugefuel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_gaugefuel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_gaugefuel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_gaugefuel1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_gaugefuel1, lv_color_hex(0x0A92D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_gaugefuel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_gaugefuel1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_gaugefuel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_gaugefuel1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_gaugefuel1, lv_color_hex(0xF77C1E), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gaugefuel1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_gaugefuel1, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_gaugefuel1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_gaugefuel1,
                                                                                                 lv_obj_get_style_pad_right(ui_gaugefuel1, LV_PART_MAIN) + 1, LV_PART_MAIN);


    ui_scalefuel1 = lv_scale_create(ui_Screen1);
            lv_obj_set_pos(ui_scalefuel1, 522, 300);
            lv_obj_set_size(ui_scalefuel1, 40, 160);
            lv_scale_set_mode(ui_scalefuel1, LV_SCALE_MODE_VERTICAL_RIGHT);
            lv_scale_set_range(ui_scalefuel1, 0, 100);
            lv_scale_set_total_tick_count(ui_scalefuel1, 21);
            lv_scale_set_major_tick_every(ui_scalefuel1, 5);
            lv_scale_set_label_show(ui_scalefuel1, true);
            lv_obj_set_style_length(ui_scalefuel1, 5, LV_PART_ITEMS | LV_STATE_DEFAULT);
            lv_obj_set_style_line_width(ui_scalefuel1, 3, LV_PART_ITEMS | LV_STATE_DEFAULT);
            lv_obj_set_style_line_rounded(ui_scalefuel1, true, LV_PART_ITEMS | LV_STATE_DEFAULT);
            lv_obj_set_style_line_color(ui_scalefuel1, lv_color_hex(0xffff0000), LV_PART_ITEMS | LV_STATE_DEFAULT);
            lv_obj_set_style_length(ui_scalefuel1, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_color(ui_scalefuel1, lv_color_hex(0xff52e80b), LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_border_color(ui_scalefuel1, lv_color_hex(0xff217ad5), LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_border_width(ui_scalefuel1, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_color(ui_scalefuel1, lv_color_hex(0xfff4422f), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(ui_scalefuel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(ui_scalefuel1, lv_color_hex(0x1f6e0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_menubutton = ui_menubutton_create(ui_Screen1);
    lv_obj_set_pos(ui_menubutton, 0, 0);


}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Container1 = NULL;
    ui_gaugerpm = NULL;
    ui_headerimg = NULL;
    ui_gaugefuel = NULL;
    ui_gaugetemp_eng = NULL;
    ui_gaugetemp = NULL;
    ui_gaugetemp_radout = NULL;
    ui_rpmbottom = NULL;
    ui_rpmtop = NULL;
    ui_Image7 = NULL;
    ui_Image14 = NULL;
    ui_Image13 = NULL;
    ui_Image12 = NULL;
    ui_Image11 = NULL;
    ui_Image10 = NULL;
    ui_Image9 = NULL;
    ui_Image8 = NULL;
    ui_gearnum = NULL;
    ui_stackedgears = NULL;
    ui_Button1 = NULL;
    ui_Button2 = NULL;
    ui_Button3 = NULL;
    ui_Button4 = NULL;
    ui_Button5 = NULL;
    ui_Button6 = NULL;
    ui_Button7 = NULL;
    ui_gaugefuel1 = NULL;
    ui_scalefuel1 = NULL;
    ui_scaletemp_eng = NULL;
    ui_scaletemp = NULL;
    ui_scaletemp_radout = NULL;
    ui_menubutton = NULL;
    //ui_menubutton1 = NULL;
    
}
