// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: t89_lvgl9_2

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Container1;
//extern lv_obj_t * ui_scale3;
extern lv_obj_t * ui_gaugerpm;
extern lv_obj_t * ui_headerimg;
extern lv_obj_t * ui_gaugefuel;
extern lv_obj_t * ui_gaugetemp_eng;
extern lv_obj_t * ui_gaugetemp;
extern lv_obj_t * ui_gaugetemp_radout;
extern lv_obj_t * ui_rpmbottom;
extern lv_obj_t * ui_rpmtop;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_gearnum;
extern lv_obj_t * ui_stackedgears;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_gaugefuel1;
extern lv_obj_t * ui_scalefuel1;
extern lv_obj_t * ui_scaletemp_eng;
extern lv_obj_t * ui_scaletemp;
extern lv_obj_t * ui_scaletemp_radout;
extern lv_obj_t * ui_menubutton;
//extern lv_obj_t * ui_menubutton1;


// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

