// Temperature Gauge Component — vertical bar + overlaid tick scale
//
// One definition shared by every temperature readout on the main screen
// (engine, radiator/Dallas, radiator outlet). Change a value in the
// UI_TEMP_GAUGE_* defines below and every instance follows.
//
// Lives here rather than in screens/ui_Screen1.c because that file carries the
// "generated by SquareLine Studio" banner — anything added to it is lost on the
// next re-export. Hand-written composites belong in components/, alongside
// ui_comp_vertical_slider and ui_comp_screen_nav_buttons.

#ifndef _UI_COMP_TEMP_GAUGE_H
#define _UI_COMP_TEMP_GAUGE_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// ── Geometry ─────────────────────────────────────────────────────────────────
#define UI_TEMP_GAUGE_MIN_C     0
#define UI_TEMP_GAUGE_MAX_C     125
#define UI_TEMP_GAUGE_W         50
#define UI_TEMP_GAUGE_H         180
#define UI_TEMP_GAUGE_SCALE_W   40
#define UI_TEMP_GAUGE_SCALE_DX  (-3)    // scale offset from its own bar —
#define UI_TEMP_GAUGE_SCALE_DY  (-10)   // keeps the ticks on the bar face
#define UI_TEMP_GAUGE_PITCH     75      // centre-to-centre spacing of instances
#define UI_TEMP_GAUGE_Y         140     // centre-relative y of every instance

// ── Colours ──────────────────────────────────────────────────────────────────
#define UI_TEMP_GAUGE_C_FACE    0xA8CFEC     // bar background
#define UI_TEMP_GAUGE_C_FILL    0x0A92D4     // bar indicator + outline
#define UI_TEMP_GAUGE_C_BORDER  0x000000
#define UI_TEMP_GAUGE_C_TICK    0xFFFF0000   // scale ticks
#define UI_TEMP_GAUGE_C_IND     0xFF52E80B   // scale indicator
#define UI_TEMP_GAUGE_C_IND_BRD 0xFF217AD5   // scale indicator border

typedef struct {
    lv_obj_t * bar;
    lv_obj_t * scale;
} ui_temp_gauge_t;

// x is a centre-relative offset; both the bar and its scale are CENTER-aligned,
// so one coordinate places the pair.
ui_temp_gauge_t ui_temp_gauge_create(lv_obj_t * comp_parent, int32_t x);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
