// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_COMP_DASHBOARDBUTTON_H
#define _UI_COMP_DASHBOARDBUTTON_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT dashboardbutton
#define UI_COMP_DASHBOARDBUTTON_DASHBOARDBUTTON 0
#define UI_COMP_DASHBOARDBUTTON_LABEL1 1
#define _UI_COMP_DASHBOARDBUTTON_NUM 2
lv_obj_t * ui_dashboardbutton_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
