// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_COMP_DASHBOARDBUTTON_HOOK_H
#define _UI_COMP_DASHBOARDBUTTON_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_dashboardbutton_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
