// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_COMP_MENUBUTTON_H
#define _UI_COMP_MENUBUTTON_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT menubutton
#define UI_COMP_MENUBUTTON_MENUBUTTON 0
#define UI_COMP_MENUBUTTON_LABEL1 1
#define _UI_COMP_MENUBUTTON_NUM 2
lv_obj_t * ui_menubutton_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
